### PR TITLE
Add ability to choose 32 verison of IEDriverServer for 64 bit node..

### PR DESCRIPTION
**Pull request by dmitryyu**
Enhancement: https://github.com/jenkinsci/selenium-plugin/issues/72
Added the option to use only 32 bit IE driver for 64 bit node.
As far as i understand, there are no needs to add the opposite option. 64 driver cannot be used for 32 bit OS.

Note:  the PR contains merged previous commits. (also refactored utils for uploading files to nodes (so Edge browser has been updated as well,)

### CODE REVIEW

**Comment by Mobrockers** [comment]
I merged your other pull request, but now cannot merge this one because you included the previous commits in it. Can you please fix your pull requests so that I can merge them? :)

**Comment by dmitryyu** [comment]
To be honest i am a bit confused with these/my branches.
I can see you have added jars... does it resolve merge issue ?  
can i do something else to resolve it?

**Comment by Mobrockers** [comment]
There are no more merge issues but unit tests are failing. If you click on details you will go to the jenkins build for this plugin and you can see which unit tests are failing. I think it might be due to needing an update to jetty but I'm not sure.

**Comment by dmitryyu** [comment]
With the latest jenkins parent plugin (https://github.com/jenkinsci/plugin-pom)  version (3.2) - jetty error is not reproduced and tests are started, selenium tests are passed (with one minor correction for a selector) but i was not able to fix issues with injected tests... (there is something with dependencies).

**Comment by dmitryyu** [comment]
@Mobrockers , Please review the commit, to be honest I am not sure if it's optimal fix, but i verified millions of possible dependencies...

**Comment by Mobrockers** [comment]
@dmitryyu Agree with fixes. Dependency conflicts are very annoying and if this fixes it then so be it. Push the changes to this branch and if the build is successful i'll merge it and try to release a new plugin version asap. The other pull request you have open is included in this pull request, right? If so, please close the other pull request.

**Comment by dmitryyu** [comment]
@Mobrockers 
Not sure you saw the PR https://github.com/jenkinsci/selenium-plugin/pull/114 . I have added missing changes. With the chhanges it's ready to release.

**Pull request merged**
