### PR TITLE
Update to selenium server standalone 2.53.0 with simpler updating mechanism

### PR DESCRIPTION
**Pull request by Mobrockers**
For this change to work, someone with jenkins maven repo access needs to run mvn package on dist-server-standalone/pom.xml to update the selenium-server-standalone version available there. If you do not have access to do this, but do have access to merge this pr and create a new plugin release, see pr #55 instead. This pr is preferred.

### CODE REVIEW

**Comment by Mobrockers** [comment]
@kinow Hey, any news so far? Have you had a chance to look at it? :)

**Comment by Mobrockers** [comment]
@kinow I have added a new mechanism for updating the selenium standalone server and have added a mechanism to update the selenium htmlunit driver. The htmlunit driver update mechanism is necessary because htmlunit driver is no longer packaged with selenium, and is thus packaged with this plugin the same way as the standalone server is packaged.

The new mechanisms make it so a plugin maintainer can now update the selenium version without needing a jenkins team member to add the dependencies to the jenkins maven.

**Comment by Mobrockers** [comment]
Please note: The one test failing on the build server does not fail locally. I get 100% success on the tests so I do not know why the node would fail to start up on the server, but success locally. I also don't really know how to find out why this is happening.

**Comment by alivespirit** [comment]
Hi,
Can someone from Jenkins team please take a look into this PR? I have built the plugin with the above changes and tested on a fully functional Selenium grid with Jenkins LTS - and it works just fine, no issues found.
It would be good to have the ability to install this plugin with the latest Selenium from plugin manager :)

Thanks!

**Pull request merged**
