### PR TITLE
Update selenium version to 2.53

### PR DESCRIPTION
**Pull request by thibaut-sticky**

### CODE REVIEW

**Comment by Mobrockers** [comment]
I literally made a pull request for this two days ago..

**Comment by thibaut-sticky** [comment]
Oh I didn't check. I will close mine. Thx. Now, we just have to wait.

**Comment by Mobrockers** [comment]
I'll look at why the build is failing today, if I can get the plugin running locally.. Never actually done any plugin development before. Then I'll drop a message to jenkins devs because the plugin maintainer has not released an update in like two years..

**Comment by thibaut-sticky** [comment]
It's surprising indeed this plugin was not updated more frequently. IMO it should be handle by the selenium repo itself.

**Comment by Mobrockers** [comment]
I think I now know why my build is failing. I could not find a selenium-server-standalone package on maven and assumed they moved it to selenium-server, but this is untrue. They have simply stopped uploading the standalone jar to maven, which is why the dist-server-standalone pom is neccesary. It add the standalone server jar to the local repository. It does not seem to do this in the build however, and I am not sure yet how to fix this. Do you have any experience with this?

**Comment by thibaut-sticky** [comment]
According to this [page](http://www.seleniumhq.org/download/maven.jsp), you can add 
```XML
<dependency>
	<groupId>org.seleniumhq.selenium</groupId>
	<artifactId>selenium-server</artifactId>
	<version>2.53.0</version>
</dependency>
```
to the pom.
>If you are using DefaultSelenium (or the RemoteWebDriver implementation), you still need to start a Selenium server. The best way is to download the selenium-server-standalone.jar from the Selenium Downloads page and just use it. Furthermore you can also embed the Selenium server into your own project, if you add the following dependency to your pom.xml.

So it should be possible to still programmaticaly start a server.

**Comment by Mobrockers** [comment]
I did change the dependencies to selenium-server instead of selenium-server-standalone but the server does not seem to start so I figure it has something to do with the way it is started by the plugin.

**Comment by Mobrockers** [comment]
It seems selenium-server does not contain the dependencies neccesary to start as a grid, and accept connecting nodes, so this is a no-go. I think I've figured out how the dependency is supposed to be loaded, but unfortunately I cannot get it working..

The pom in dist-server-standalone that is used to load the selenium-server-standalone dependency tries to upload it to http://maven.jenkins-ci.org:8081/content/repositories/releases, but this repository does not seem to exist, or I do not have rights to it..

**Comment by Mobrockers** [comment]
I have figured out how it all works, kinda. I have created a post on the jenkins developers mailing list and made two new pull requests. It is now up to a jenkins member to make the neccesary changes and release a new plugin version.

**Comment by kinow** [comment]
@Mobrockers I haven't used the plug-in in a while, but if there's no activity ping me and I'll check if I can help. Not a maintainer of the plug-in, but know the maintainer and could try to ping him or ask if we can release it ;-)

Thanks for the enthusiasm. Have your post in the dev mailing list in my e-mail inbox, and will read it with more calm later this weekend. I'm on vacations, decided to make it an Open Source vacation :D

**Comment by Mobrockers** [comment]
@kinow Thank you, will do! I'm working on implementing selenium as part of my internship and I want to leave them with a stable and up to date base framework so I'm trying to put in the effort and help out where I can. It's more fun than writing internship reports anyway :) Have a nice vacation!

**Pull request closed without merging**
