### PR TITLE
remove "-host" for bind on all ip (0.0.0.0)

### PR DESCRIPTION
**Pull request by qxo**
when run jenkins on docker container
if selenium hub bind on all ip ,thenwet using docker host ip  at "Hostname resolver" (Use a fixed hostname )

### CODE REVIEW

**Comment by burdandrei** [comment]
This would be great, and will eliminate all the monkey patching if the Jenkins is behind the load balancer

**Comment by Mobrockers** [comment]
I'm sorry but I cannot merge this pull request without a better explanation for why it is useful. You have also not cleaned up any of the left-over code associated with hostname resolving, even though this "fix" makes that setting completely useless. If this was an extra option in the hostname resolver, and you could explain why this is necessary I could determine if this is wanted or not, but currently I'll have to deny this pr.

**Comment by Mobrockers** [comment]
@qxo @burdandrei Do either of you still require this feature? I have a plugin update to test that implements this in a more sane way than this pull request did. You can test it by loading this plugin update: https://dl.dropboxusercontent.com/u/5483751/selenium.hpi

And setting Selenium hostname resolver in Jenkins global configuration to no hostname resolver

**Comment by burdandrei** [comment]
https://github.com/jenkinsci/selenium-plugin/issues/60#issuecomment-224047510

*____________________*
*Andrei Burd*
*Tel: +972 (546) 46 22 36*
*Skype: burdandrei*

**Comment by burdandrei** [comment]
@Mobrockers  https://github.com/jenkinsci/selenium-plugin/issues/60#issuecomment-224047510

**Pull request closed without merging**
